#!/bin/bash

pushd . > /dev/null
SCRIPT_PATH="${BASH_SOURCE[0]}";
if ([ -h "${SCRIPT_PATH}" ]) then
	while([ -h "${SCRIPT_PATH}" ])
	do
		cd `dirname "$SCRIPT_PATH"`;
		SCRIPT_PATH=`readlink "${SCRIPT_PATH}"`;
		echo $SCRIPT_PATH
	done
fi
cd `dirname ${SCRIPT_PATH}` > /dev/null
SCRIPT_PATH=`pwd`;
popd  > /dev/null

export NODE_OPTIONS="-r $SCRIPT_PATH/node_modules/@std/esm $NODE_OPTIONS"
export ESM_OPTIONS="$(jq -c '.["@std/esm"]' $SCRIPT_PATH/package.json)"
node -r $SCRIPT_PATH/node_modules/@std/esm $SCRIPT_PATH/main-run.js $*
